const express = require('express')
const router = express.Router()
const homeController = require('../../controllers/customerController/homeController')
const verifyToken = require('../../middlewares/userMiddleware')
const verifyUser = require('../../middlewares/verifyUserMiddleware')

router.post('/addFavoritesProviders',verifyToken,verifyUser,homeController.addFavoritesProviders)
router.post('/favoriteListing',verifyToken,verifyUser,homeController.favoriteListing)
router.post('/getProviders',verifyToken,verifyUser,homeController.getProviders)
router.post('/getSellingItems',verifyToken,verifyUser,homeController.getSellingItems)
router.post('/placeOrder',verifyToken,verifyUser,homeController.placeOrder)
router.post('/myOrders',verifyToken,verifyUser,homeController.myOrders)
router.post('/myItemOrders',verifyToken,verifyUser,homeController.myItemOrders)
router.post('/orderDetails',verifyToken,verifyUser,homeController.orderDetails)
router.post('/itemOrderDetails',verifyToken,verifyUser,homeController.itemOrderDetails)
router.post('/chooseServices',verifyToken,verifyUser,homeController.chooseServices)
router.post('/viewProvider',verifyToken,verifyUser,homeController.viewProvider)
router.post('/applyPromoCode',verifyToken,verifyUser,homeController.applyPromoCode)
router.post('/getCartData',verifyToken,verifyUser,homeController.getCartData)
router.post('/rateSellingOrder',verifyToken,verifyUser,homeController.rateSellingOrder)
router.post('/rateOrder',verifyToken,verifyUser,homeController.rateOrder)
router.post('/modifyOrder',verifyToken,verifyUser,homeController.modifyOrder)
router.post('/modifyItemOrder',verifyToken,verifyUser,homeController.modifyItemOrder)
router.post('/getUpdatedCartItem',verifyToken,verifyUser,homeController.getUpdatedCartItem)
router.post('/itemDetails',verifyToken,verifyUser,homeController.itemDetails)
router.post('/addItemToCart',verifyToken,verifyUser,homeController.addItemToCart)
router.get('/getCartItem',verifyToken,verifyUser,homeController.getCartItem)
router.post('/placeItemOrder',verifyToken,verifyUser,homeController.placeItemOrder)

module.exports = router;