const express = require('express')
const router = express.Router()
const paymentController = require('../../controllers/serviceProviderController/paymentController')
const verifyProviderToken = require('../../middlewares/providerMiddleware')
const verifyProvider = require('../../middlewares/verifyProviderMiddleware')
const verifyCustomerToken = require('../../middlewares/userMiddleware')
const verifyCustomer = require('../../middlewares/verifyUserMiddleware')

 router.get('/createAccount',verifyProviderToken,verifyProvider,paymentController.createAccount)
 router.get('/refreshURL/:providerId',paymentController.refreshURL)
 router.get('/returnURL/:providerId',paymentController.returnURL)
 router.get('/test',paymentController.test)
 router.post('/customerGoogleReceipt',verifyCustomerToken,verifyCustomer,paymentController.customerGoogleReceipt)
 router.post('/providerGoogleReceipt',verifyProviderToken,verifyProvider,paymentController.providerGoogleReceipt)
 router.post('/customerAppleReceipt',verifyCustomerToken,verifyCustomer,paymentController.customerAppleReceipt)
 router.post('/providerAppleReceipt',verifyProviderToken,verifyProvider,paymentController.providerAppleReceipt)
 router.post('/providerGoogleWebHook',paymentController.providerGoogleWebHook)
 router.post('/appleWebHook',paymentController.appleWebHook)
module.exports = router;